apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}-service
  namespace: wikistats
  labels:
    app: {{ .Chart.Name }}
spec:
  selector:
    app: {{ .Chart.Name }}
  ports:
    - name: metrics       
      protocol: TCP
      port: 7000          
      targetPort: 7000