apiVersion: v1
kind: Service
metadata:
  name: scylla
  namespace: wikistats
spec:
  clusterIP: None
  ports:
    - name: cql
      port: 9042
    - name: metrics
      port: 9180
  selector:
    app: scylla