{
 "title": "Wikistats Consumer",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Successful Processed Events",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "wiki_redpanda_events_processed_successfully",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Redpanda Events Consumed",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    { "expr": "wiki_redpanda_events_consumed", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Failed Processed Events",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "wiki_redpanda_events_processed_failed",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}